#! /bin/sh
set -e

version=`uname -r`

# passing the kernel version is required
[ -z "$version" ] && exit 1

if [ -f /boot/initrd.img-$version ]; then
	mkimage -A arm -O linux -T ramdisk -C gzip -a 0 -e 0 -n uInitrd -d /boot/initrd.img-$version /boot/uInitrd-$version

	# checking if /media boot exists if so, then copy uInitrd there (should be Ubuntu)
	if [ ! -d /media/boot ]; then
		cp /boot/uInitrd-$version /boot/uInitrd
	else
		cp /boot/uInitrd-$version /media/boot/uInitrd
	fi
else
	true
fi
